
CREATE DATABASE IF NOT EXISTS `discob`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `discob`;
CREATE TABLE IF NOT EXISTS `accounts` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(20) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `AccountToken` VARCHAR(255) NOT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uq_accounts_username` (`Username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `messages` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RoomID` VARCHAR(64) NOT NULL,
  `MessageText` TEXT NOT NULL,
  `MessageDate` BIGINT NOT NULL,
  `Username` VARCHAR(20) NOT NULL,
  `DisplayName` VARCHAR(255) DEFAULT NULL,
  `UserID` BIGINT UNSIGNED DEFAULT NULL,
  `MessageID` CHAR(36) NOT NULL DEFAULT (UUID()),
  `UserColor` VARCHAR(32) NOT NULL,
  `Reply` LONGTEXT DEFAULT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_messages_room_date` (`RoomID`, `MessageDate`),
  CONSTRAINT `fk_messages_username`
    FOREIGN KEY (`Username`) REFERENCES `accounts` (`Username`)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
